package brc

import (
	"hash/fnv"
	"testing"

	"github.com/cespare/xxhash/v2"
	"github.com/stretchr/testify/assert"
	"github.com/zeebo/xxh3"
)

var names = [][]byte{
	[]byte("Abha"),
	[]byte("Abidjan"),
	[]byte("Abéché"),
	[]byte("Accra"),
	[]byte("Addis Ababa"),
	[]byte("Adelaide"),
	[]byte("Aden"),
	[]byte("Ahvaz"),
	[]byte("Albuquerque"),
	[]byte("Alexandra"),
	[]byte("Alexandria"),
	[]byte("Algiers"),
	[]byte("Alice Springs"),
	[]byte("Almaty"),
	[]byte("Amsterdam"),
	[]byte("Anadyr"),
	[]byte("Anchorage"),
	[]byte("Andorra la Vella"),
	[]byte("Ankara"),
	[]byte("Antananarivo"),
	[]byte("Antsiranana"),
	[]byte("Arkhangelsk"),
	[]byte("Ashgabat"),
	[]byte("Asmara"),
	[]byte("Assab"),
	[]byte("Astana"),
	[]byte("Athens"),
	[]byte("Atlanta"),
	[]byte("Auckland"),
	[]byte("Austin"),
	[]byte("Baghdad"),
	[]byte("Baguio"),
	[]byte("Baku"),
	[]byte("Baltimore"),
	[]byte("Bamako"),
	[]byte("Bangkok"),
	[]byte("Bangui"),
	[]byte("Banjul"),
	[]byte("Barcelona"),
	[]byte("Bata"),
	[]byte("Batumi"),
	[]byte("Beijing"),
	[]byte("Beirut"),
	[]byte("Belgrade"),
	[]byte("Belize City"),
	[]byte("Benghazi"),
	[]byte("Bergen"),
	[]byte("Berlin"),
	[]byte("Bilbao"),
	[]byte("Birao"),
	[]byte("Bishkek"),
	[]byte("Bissau"),
	[]byte("Blantyre"),
	[]byte("Bloemfontein"),
	[]byte("Boise"),
	[]byte("Bordeaux"),
	[]byte("Bosaso"),
	[]byte("Boston"),
	[]byte("Bouaké"),
	[]byte("Bratislava"),
	[]byte("Brazzaville"),
	[]byte("Bridgetown"),
	[]byte("Brisbane"),
	[]byte("Brussels"),
	[]byte("Bucharest"),
	[]byte("Budapest"),
	[]byte("Bujumbura"),
	[]byte("Bulawayo"),
	[]byte("Burnie"),
	[]byte("Busan"),
	[]byte("Cabo San Lucas"),
	[]byte("Cairns"),
	[]byte("Cairo"),
	[]byte("Calgary"),
	[]byte("Canberra"),
	[]byte("Cape Town"),
	[]byte("Changsha"),
	[]byte("Charlotte"),
	[]byte("Chiang Mai"),
	[]byte("Chicago"),
	[]byte("Chihuahua"),
	[]byte("Chittagong"),
	[]byte("Chișinău"),
	[]byte("Chongqing"),
	[]byte("Christchurch"),
	[]byte("City of San Marino"),
	[]byte("Colombo"),
	[]byte("Columbus"),
	[]byte("Conakry"),
	[]byte("Copenhagen"),
	[]byte("Cotonou"),
	[]byte("Cracow"),
	[]byte("Da Lat"),
	[]byte("Da Nang"),
	[]byte("Dakar"),
	[]byte("Dallas"),
	[]byte("Damascus"),
	[]byte("Dampier"),
	[]byte("Dar es Salaam"),
	[]byte("Darwin"),
	[]byte("Denpasar"),
	[]byte("Denver"),
	[]byte("Detroit"),
	[]byte("Dhaka"),
	[]byte("Dikson"),
	[]byte("Dili"),
	[]byte("Djibouti"),
	[]byte("Dodoma"),
	[]byte("Dolisie"),
	[]byte("Douala"),
	[]byte("Dubai"),
	[]byte("Dublin"),
	[]byte("Dunedin"),
	[]byte("Durban"),
	[]byte("Dushanbe"),
	[]byte("Edinburgh"),
	[]byte("Edmonton"),
	[]byte("El Paso"),
	[]byte("Entebbe"),
	[]byte("Erbil"),
	[]byte("Erzurum"),
	[]byte("Fairbanks"),
	[]byte("Fianarantsoa"),
	[]byte("Flores,  Petén"),
	[]byte("Frankfurt"),
	[]byte("Fresno"),
	[]byte("Fukuoka"),
	[]byte("Gaborone"),
	[]byte("Gabès"),
	[]byte("Gagnoa"),
	[]byte("Gangtok"),
	[]byte("Garissa"),
	[]byte("Garoua"),
	[]byte("George Town"),
	[]byte("Ghanzi"),
	[]byte("Gjoa Haven"),
	[]byte("Guadalajara"),
	[]byte("Guangzhou"),
	[]byte("Guatemala City"),
	[]byte("Halifax"),
	[]byte("Hamburg"),
	[]byte("Hamilton"),
	[]byte("Hanga Roa"),
	[]byte("Hanoi"),
	[]byte("Harare"),
	[]byte("Harbin"),
	[]byte("Hargeisa"),
	[]byte("Hat Yai"),
	[]byte("Havana"),
	[]byte("Helsinki"),
	[]byte("Heraklion"),
	[]byte("Hiroshima"),
	[]byte("Ho Chi Minh City"),
	[]byte("Hobart"),
	[]byte("Hong Kong"),
	[]byte("Honiara"),
	[]byte("Honolulu"),
	[]byte("Houston"),
	[]byte("Ifrane"),
	[]byte("Indianapolis"),
	[]byte("Iqaluit"),
	[]byte("Irkutsk"),
	[]byte("Istanbul"),
	[]byte("Jacksonville"),
	[]byte("Jakarta"),
	[]byte("Jayapura"),
	[]byte("Jerusalem"),
	[]byte("Johannesburg"),
	[]byte("Jos"),
	[]byte("Juba"),
	[]byte("Kabul"),
	[]byte("Kampala"),
	[]byte("Kandi"),
	[]byte("Kankan"),
	[]byte("Kano"),
	[]byte("Kansas City"),
	[]byte("Karachi"),
	[]byte("Karonga"),
	[]byte("Kathmandu"),
	[]byte("Khartoum"),
	[]byte("Kingston"),
	[]byte("Kinshasa"),
	[]byte("Kolkata"),
	[]byte("Kuala Lumpur"),
	[]byte("Kumasi"),
	[]byte("Kunming"),
	[]byte("Kuopio"),
	[]byte("Kuwait City"),
	[]byte("Kyiv"),
	[]byte("Kyoto"),
	[]byte("La Ceiba"),
	[]byte("La Paz"),
	[]byte("Lagos"),
	[]byte("Lahore"),
	[]byte("Lake Havasu City"),
	[]byte("Lake Tekapo"),
	[]byte("Las Palmas de Gran Canaria"),
	[]byte("Las Vegas"),
	[]byte("Launceston"),
	[]byte("Lhasa"),
	[]byte("Libreville"),
	[]byte("Lisbon"),
	[]byte("Livingstone"),
	[]byte("Ljubljana"),
	[]byte("Lodwar"),
	[]byte("Lomé"),
	[]byte("London"),
	[]byte("Los Angeles"),
	[]byte("Louisville"),
	[]byte("Luanda"),
	[]byte("Lubumbashi"),
	[]byte("Lusaka"),
	[]byte("Luxembourg City"),
	[]byte("Lviv"),
	[]byte("Lyon"),
	[]byte("Madrid"),
	[]byte("Mahajanga"),
	[]byte("Makassar"),
	[]byte("Makurdi"),
	[]byte("Malabo"),
	[]byte("Malé"),
	[]byte("Managua"),
	[]byte("Manama"),
	[]byte("Mandalay"),
	[]byte("Mango"),
	[]byte("Manila"),
	[]byte("Maputo"),
	[]byte("Marrakesh"),
	[]byte("Marseille"),
	[]byte("Maun"),
	[]byte("Medan"),
	[]byte("Mek'ele"),
	[]byte("Melbourne"),
	[]byte("Memphis"),
	[]byte("Mexicali"),
	[]byte("Mexico City"),
	[]byte("Miami"),
	[]byte("Milan"),
	[]byte("Milwaukee"),
	[]byte("Minneapolis"),
	[]byte("Minsk"),
	[]byte("Mogadishu"),
	[]byte("Mombasa"),
	[]byte("Monaco"),
	[]byte("Moncton"),
	[]byte("Monterrey"),
	[]byte("Montreal"),
	[]byte("Moscow"),
	[]byte("Mumbai"),
	[]byte("Murmansk"),
	[]byte("Muscat"),
	[]byte("Mzuzu"),
	[]byte("N'Djamena"),
	[]byte("Naha"),
	[]byte("Nairobi"),
	[]byte("Nakhon Ratchasima"),
	[]byte("Napier"),
	[]byte("Napoli"),
	[]byte("Nashville"),
	[]byte("Nassau"),
	[]byte("Ndola"),
	[]byte("New Delhi"),
	[]byte("New Orleans"),
	[]byte("New York City"),
	[]byte("Ngaoundéré"),
	[]byte("Niamey"),
	[]byte("Nicosia"),
	[]byte("Niigata"),
	[]byte("Nouadhibou"),
	[]byte("Nouakchott"),
	[]byte("Novosibirsk"),
	[]byte("Nuuk"),
	[]byte("Odesa"),
	[]byte("Odienné"),
	[]byte("Oklahoma City"),
	[]byte("Omaha"),
	[]byte("Oranjestad"),
	[]byte("Oslo"),
	[]byte("Ottawa"),
	[]byte("Ouagadougou"),
	[]byte("Ouahigouya"),
	[]byte("Ouarzazate"),
	[]byte("Oulu"),
	[]byte("Palembang"),
	[]byte("Palermo"),
	[]byte("Palm Springs"),
	[]byte("Palmerston North"),
	[]byte("Panama City"),
	[]byte("Parakou"),
	[]byte("Paris"),
	[]byte("Perth"),
	[]byte("Petropavlovsk-Kamchatsky"),
	[]byte("Philadelphia"),
	[]byte("Phnom Penh"),
	[]byte("Phoenix"),
	[]byte("Pittsburgh"),
	[]byte("Podgorica"),
	[]byte("Pointe-Noire"),
	[]byte("Pontianak"),
	[]byte("Port Moresby"),
	[]byte("Port Sudan"),
	[]byte("Port Vila"),
	[]byte("Port-Gentil"),
	[]byte("Portland (OR)"),
	[]byte("Porto"),
	[]byte("Prague"),
	[]byte("Praia"),
	[]byte("Pretoria"),
	[]byte("Pyongyang"),
	[]byte("Rabat"),
	[]byte("Rangpur"),
	[]byte("Reggane"),
	[]byte("Reykjavík"),
	[]byte("Riga"),
	[]byte("Riyadh"),
	[]byte("Rome"),
	[]byte("Roseau"),
	[]byte("Rostov-on-Don"),
	[]byte("Sacramento"),
	[]byte("Saint Petersburg"),
	[]byte("Saint-Pierre"),
	[]byte("Salt Lake City"),
	[]byte("San Antonio"),
	[]byte("San Diego"),
	[]byte("San Francisco"),
	[]byte("San Jose"),
	[]byte("San José"),
	[]byte("San Juan"),
	[]byte("San Salvador"),
	[]byte("Sana'a"),
	[]byte("Santo Domingo"),
	[]byte("Sapporo"),
	[]byte("Sarajevo"),
	[]byte("Saskatoon"),
	[]byte("Seattle"),
	[]byte("Seoul"),
	[]byte("Seville"),
	[]byte("Shanghai"),
	[]byte("Singapore"),
	[]byte("Skopje"),
	[]byte("Sochi"),
	[]byte("Sofia"),
	[]byte("Sokoto"),
	[]byte("Split"),
	[]byte("St. John's"),
	[]byte("St. Louis"),
	[]byte("Stockholm"),
	[]byte("Surabaya"),
	[]byte("Suva"),
	[]byte("Suwałki"),
	[]byte("Sydney"),
	[]byte("Ségou"),
	[]byte("Tabora"),
	[]byte("Tabriz"),
	[]byte("Taipei"),
	[]byte("Tallinn"),
	[]byte("Tamale"),
	[]byte("Tamanrasset"),
	[]byte("Tampa"),
	[]byte("Tashkent"),
	[]byte("Tauranga"),
	[]byte("Tbilisi"),
	[]byte("Tegucigalpa"),
	[]byte("Tehran"),
	[]byte("Tel Aviv"),
	[]byte("Thessaloniki"),
	[]byte("Thiès"),
	[]byte("Tijuana"),
	[]byte("Timbuktu"),
	[]byte("Tirana"),
	[]byte("Toamasina"),
	[]byte("Tokyo"),
	[]byte("Toliara"),
	[]byte("Toluca"),
	[]byte("Toronto"),
	[]byte("Tripoli"),
	[]byte("Tromsø"),
	[]byte("Tucson"),
	[]byte("Tunis"),
	[]byte("Ulaanbaatar"),
	[]byte("Upington"),
	[]byte("Vaduz"),
	[]byte("Valencia"),
	[]byte("Valletta"),
	[]byte("Vancouver"),
	[]byte("Veracruz"),
	[]byte("Vienna"),
	[]byte("Vientiane"),
	[]byte("Villahermosa"),
	[]byte("Vilnius"),
	[]byte("Virginia Beach"),
	[]byte("Vladivostok"),
	[]byte("Warsaw"),
	[]byte("Washington, D.C."),
	[]byte("Wau"),
	[]byte("Wellington"),
	[]byte("Whitehorse"),
	[]byte("Wichita"),
	[]byte("Willemstad"),
	[]byte("Winnipeg"),
	[]byte("Wrocław"),
	[]byte("Xi'an"),
	[]byte("Yakutsk"),
	[]byte("Yangon"),
	[]byte("Yaoundé"),
	[]byte("Yellowknife"),
	[]byte("Yerevan"),
	[]byte("Yinchuan"),
	[]byte("Zagreb"),
	[]byte("Zanzibar City"),
	[]byte("Zürich"),
	[]byte("Ürümqi"),
	[]byte("İzmir"),
}

func benchmarkHash(b *testing.B, hashFunc func([]byte) uint32) {
	for i := 0; i < b.N; i++ {
		for _, s := range names {
			hashFunc(s)
		}
	}
}

var patate = xxhash.New()

func xxHashNew(b []byte) uint32 {
	patate.Reset()
	patate.Write(b)
	return uint32(patate.Sum64()) // XXX bad but just for speed test
}

func xxHash(b []byte) uint32 {
	return uint32(xxhash.Sum64(b)) // XXX bad but just for speed test
}

func xxh3F(b []byte) uint32 {
	return uint32(xxh3.Hash(b))
}

func BenchmarkHashByteXxHashNew64(b *testing.B)     { benchmarkHash(b, xxHashNew) }
func BenchmarkHashByteXxHash64(b *testing.B)        { benchmarkHash(b, xxHash) }
func BenchmarkHashByteXxh3(b *testing.B)            { benchmarkHash(b, xxh3F) }
func BenchmarkHashByteHashUnrolled4(b *testing.B)   { benchmarkHash(b, byteHash) }
func BenchmarkHashFnv1a(b *testing.B)               { benchmarkHash(b, fnv1a) }
func BenchmarkHashFnv1aRangeIndex(b *testing.B)     { benchmarkHash(b, fnv1aRangeIndex) }
func BenchmarkHashFnv1aRange(b *testing.B)          { benchmarkHash(b, fnv1aRange) }
func BenchmarkHashByteHashUnrolledBCE(b *testing.B) { benchmarkHash(b, ByteHashBCE) }
func BenchmarkHashStdlibFnv1a(b *testing.B) {
	hasher := fnv.New32a()
	benchmarkHash(b, func(b []byte) uint32 {
		hasher.Reset()
		hasher.Write(b)
		return hasher.Sum32()
	})
}

func TestHash(t *testing.T) {
	for _, s := range names {
		assert.Equal(t, byteHash(s), fnv1a(s))
		assert.Equal(t, byteHash(s), ByteHashBCE(s))
	}
}
